# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itservices', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstrVirtualSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterMapComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('itservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HostInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSystemsAggregated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('tag1', models.CharField(blank=True, max_length=75)),
                ('tag2', models.CharField(blank=True, max_length=75)),
                ('tag3', models.CharField(blank=True, max_length=75)),
                ('check1', models.BooleanField()),
                ('check2', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.Group')),
                ('itservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Landspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualizationTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('abstrvirtualsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.AbstrVirtualSystem')),
                ('virtualization_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('systems.abstrvirtualsystem',),
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('abstrvirtualsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.AbstrVirtualSystem')),
                ('virtualization_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('systems.abstrvirtualsystem',),
        ),
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='virtualization_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
        migrations.AddField(
            model_name='hostinstance',
            name='virtualization_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
        migrations.AddField(
            model_name='computer',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Computer'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.ComputerRole'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='cluster_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.ClusterTechnology'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='itservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='abstrvirtualsystem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='abstrvirtualsystem',
            name='itservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='abstrvirtualsystem',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
    ]
