# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itservices', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMapComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComputerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenericSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('is_host', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('tag1', models.CharField(blank=True, max_length=75, null=True)),
                ('tag2', models.CharField(blank=True, max_length=75, null=True)),
                ('tag3', models.CharField(blank=True, max_length=75, null=True)),
                ('check1', models.BooleanField()),
                ('check2', models.BooleanField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itservices.Group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Landspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualizationTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('genericsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.GenericSystem')),
                ('cluster_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.ClusterTechnology')),
            ],
            options={
                'abstract': False,
            },
            bases=('systems.genericsystem',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('genericsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.GenericSystem')),
            ],
            options={
                'abstract': False,
            },
            bases=('systems.genericsystem',),
        ),
        migrations.CreateModel(
            name='GenericVirtualSystem',
            fields=[
                ('genericsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.GenericSystem')),
            ],
            options={
                'abstract': False,
            },
            bases=('systems.genericsystem',),
        ),
        migrations.AddField(
            model_name='importsystems',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.GenericSystem'),
        ),
        migrations.AddField(
            model_name='importsystems',
            name='itservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='importsystems',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='importsystems',
            name='virtualization_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
        migrations.AddField(
            model_name='genericsystem',
            name='itservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
        migrations.AddField(
            model_name='genericsystem',
            name='landspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace'),
        ),
        migrations.AddField(
            model_name='genericsystem',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_systems.genericsystem_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.ComputerRole'),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('genericvirtualsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.GenericVirtualSystem')),
            ],
            options={
                'abstract': False,
            },
            bases=('systems.genericvirtualsystem',),
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('genericvirtualsystem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.GenericVirtualSystem')),
            ],
            options={
                'abstract': False,
            },
            bases=('systems.genericvirtualsystem',),
        ),
        migrations.AddField(
            model_name='genericvirtualsystem',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstrvirtualsystem_host_ptr', to='systems.GenericSystem'),
        ),
        migrations.AddField(
            model_name='genericvirtualsystem',
            name='virtualization_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Cluster'),
        ),
        migrations.AddField(
            model_name='clustermapcomputer',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Computer'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='computers',
            field=models.ManyToManyField(through='systems.ClusterMapComputer', to='systems.Computer'),
        ),
    ]
