# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20160330_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericvirtualsystem',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genericvirtualsystem_host_ptr', to='systems.GenericSystem'),
        ),
    ]
