# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('systems', '0018_auto_20160312_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='host_plug',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='host_plug',
        ),
        migrations.AddField(
            model_name='hostplug',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostplug',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
