# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('itservices', '0002_auto_20160308_2022'),
        ('systems', '0019_auto_20160316_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstrVirtualSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('itservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService')),
                ('landspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.Landspace')),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='hostplug',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='container',
            name='description',
        ),
        migrations.RemoveField(
            model_name='container',
            name='host',
        ),
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.RemoveField(
            model_name='container',
            name='itservice',
        ),
        migrations.RemoveField(
            model_name='container',
            name='landspace',
        ),
        migrations.RemoveField(
            model_name='container',
            name='name',
        ),
        migrations.RemoveField(
            model_name='container',
            name='note',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='host',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='itservice',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='landspace',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='note',
        ),
        migrations.DeleteModel(
            name='HostPlug',
        ),
        migrations.AddField(
            model_name='container',
            name='abstrvirtualsystem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.AbstrVirtualSystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='abstrvirtualsystem_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systems.AbstrVirtualSystem'),
            preserve_default=False,
        ),
    ]
