# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itservices', '0002_auto_20160308_2022'),
        ('systems', '0021_importsystemsaggregated'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itservices.Group'),
            preserve_default=False,
        ),
    ]
