# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0023_auto_20160317_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='check1',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='check2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='virtualization_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
        migrations.AlterField(
            model_name='importsystemsaggregated',
            name='itservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
    ]
