# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0024_auto_20160317_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsystemsaggregated',
            name='itservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itservices.ITService'),
        ),
    ]
