# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0025_auto_20160317_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='virtualization_technology',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
            preserve_default=False,
        ),
    ]
