# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0026_importsystemsaggregated_virtualization_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsystemsaggregated',
            name='virtualization_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.VirtualizationTechnology'),
        ),
    ]
