# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0027_auto_20160317_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='check1',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importsystemsaggregated',
            name='check2',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
