# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0028_auto_20160317_1806'),
        ('systems', '0024_auto_20160317_1830'),
    ]

    operations = [
    ]
