# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('vendor', models.CharField(max_length=75)),
                ('arch', models.CharField(max_length=75)),
                ('frequency', models.CharField(max_length=75)),
                ('cores', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GraphicAdapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Harddisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=75)),
                ('vendor', models.CharField(max_length=75)),
                ('size_sectors', models.IntegerField()),
                ('sector_size', models.IntegerField()),
                ('serial', models.CharField(max_length=75)),
                ('revision', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=75)),
                ('vendor', models.CharField(max_length=75)),
                ('technology', models.CharField(max_length=75)),
                ('number_ports', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
