# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Computer'),
        ),
    ]
